### PR TITLE
Adds tests, moves to null safety

### PR DESCRIPTION
**Pull request by stargazing-dino**
This is a fairly large PR sorry. I originally was just going to make another package but I'd rather contribute to one instead

 - [x] Adds tests
 - [x] Better analysis (Moved to strong mode)
 - [x] Moves to null safety
 - [x] Add parser from `intl_translation`
 - [x] Only translate text and not placeholders or arguments

Let me know what you think.

### CODE REVIEW

**Comment by justkawal** [comment]
@Nolence 
Thanks buddy,
I've seen you had done a lot of work in it, which is truly awesome.
I'll be waiting for your final pull-request.

You know because of people like you, Open Source is improving everyday. and this is the reason why I love Open Source work.

If I'll be receiving any donations from this package from today onwards, I'll be happy to share the donations with you buddy.

~ Best
~ Kawaljeet Singh
Long Live 🔥pen Source

**Comment by stargazing-dino** [comment]
Thank you for the encouragement! I really appreciate it :)

No worries about the donation thing. I'm just looking for reliable code for my own selfish reasons haha! I should be ready for a review soon once I think how best to implement only translating text and not placeholders or other misc text

**Comment by justkawal** [comment]
> Thank you for the encouragement! I really appreciate it :)
> 
> No worries about the donation thing. I'm just looking for reliable code for my own selfish reasons haha! I should be ready for a review soon once I think how best to implement only translating text and not placeholders or other misc text

@Nolence 
That's so humble of you to think like that. 💯 
and yeah you can't say no to me on the donation thing. 😄 

Thanks for the hardwork.

**Comment by stargazing-dino** [comment]
My sample translation

```arb
{
  "@@locale": "es",
  "appName": "Demo app",
  "pageLoginUsername": "Su nombre de usuario",
  "@pageLoginUsername": {},
  "pageLoginPassword": "Tu contraseña",
  "@pageLoginPassword": {},
  "pageHomeTitle": "Bienvenido {firstName}",
  "@pageHomeTitle": {
    "description": "Welcome message on the Home screen",
    "placeholders": {
      "firstName": {}
    }
  },
  "pageHomeInboxCount": "{count, plural, zero{No tienes mensajes nuevos} one{Tienes 1 mensaje nuevo} other{Has {count} mensajes nuevos}}",
  "@pageHomeInboxCount": {
    "description": "New messages count on the Home screen",
    "placeholders": {
      "count": {}
    }
  },
  "pageHomeBirthday": "{sex, select, male{Su cumpleaños} female{Su cumpleaños} other{Su cumpleaños}}",
  "@pageHomeBirthday": {
    "description": "Birthday message on the Home screen",
    "placeholders": {
      "sex": {}
    }
  },
  "commonVehicleType": "{vehicleType, select, sedan{Entonces} cabriolet{Cabriolet de techo macizo} truck{Camión de 16 ruedas} other{Otro}}",
  "@commonVehicleType": {
    "description": "Vehicle type",
    "placeholders": {
      "vehicleType": {}
    }
  }
}
```

I'll create a couple more issues for misc improvements I intend to do but not now. Otherwise, give it a try and let me know how it works

**Pull request merged**
